Description: cariad/hugo-ci test infrastructure
Resources:

  CI:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: Publish
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action: s3:ListBucket
                Effect: Allow
                Resource:
                  Fn::Sub: arn:aws:s3:::${Bucket}
              - Action:
                  - s3:DeleteObject
                  - s3:GetObject
                  - s3:PutObject
                Effect: Allow
                Resource:
                  Fn::Sub: arn:aws:s3:::${Bucket}/*

  Bucket:
    Type: AWS::S3::Bucket
