name: on-push

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  test:
    container: cariad/ci:1.4.0
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - id: cache-venv
        uses: actions/cache@v1
        with:
          key: ${{ runner.os }}-venv-${{ hashFiles('Pipfile.lock') }}
          path: ~/.local/share/virtualenvs

      - if: steps.cache-venv.outputs.cache-hit != 'true'
        run: pipenv sync --dev

      - run: pipenv run ./test-boilerplate.sh

  build:
    needs:
      - test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - id: buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ github.ref }}
          restore-keys: buildx-

      - id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: cariad/hugo-ci

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          labels: ${{ steps.docker_meta.outputs.labels }}
          pull: true
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}

  verify:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      ROOT_TEST_BUCKET: hugoci-test-roothost-7pf9gl48qv5q
      PREFIX_TEST_BUCKET: hugoci-test-prefixhost-1sxegmx69s42v
    needs:
      - build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: ./test-image.sh
